### ISSUE TITLE
Implement textual changes in preparation for launch

### ISSUE THREAD

**Issue by gtsueng** [NIAID-Data-Ecosystem/nde-portal#185]
The deadline for textual changes is July 7th.

Textual changes have been suggested for the following issues and are awaiting finalization from the NIAID team:
- [x] [Disclaimer text (to be added to "Interpret Search Results Carefully" section of the About page)](https://github.com/NIAID-Data-Ecosystem/niaid-feedback/issues/62)
  - [x] The text has been provided
  - [ ] The text will not be provided
- [x] [About page Partnership text updates](https://github.com/NIAID-Data-Ecosystem/niaid-feedback/issues/64)
  - [x] The text has been provided
  - [ ] The text will not be provided
- [x] [Sentence explaining homepage if needed/desired](https://github.com/NIAID-Data-Ecosystem/niaid-feedback/issues/59)
  - [ ] The text has been provided
  - [x] The text will not be provided
