### ISSUE TITLE
[User Interface: Redesign]: Add subtotals to hover over explanation of metadata completeness badge

### ISSUE THREAD

**Issue by gtsueng** [NIAID-Data-Ecosystem/nde-portal#219]
### Issue Name

Add subtotals to hover over explanation of metadata completeness badge

### Issue Description

There was a request to provide a legend for the metadata badges. The hover-over image already does the job, but the NIAID team requested that it be made more informative:

This was the change we proposed to make it more informative:
![image](https://github.com/NIAID-Data-Ecosystem/nde-portal/assets/9200138/9187ddb7-645c-4022-b307-4a0e76996c57)

The context: a repository owner wanted to know the missing fields in the legend, and the NIAID team requested that the legend be made more informative to accommodate the repo owner's request. We discussed the flaw of this approach in that it may upset users who submitted data to a repository, but are unable to address the completeness issue, since it is limited at the repository level, so it would not make sense for the record-level badge. Adding the subtotals to the hover-over 'legend' of the completeness badge will make it more informative without introducing the issues with the missing fields.

### Issue Discussion

This was discussed at the biweekly meeting dated 2023.01.30

### WCAG Compliance Check

- [X] The ui changes are not expected to significantly affect WCAG compliance (ex- wording changes)
- [ ] The ui changes have visual elements which have yet to be tested for WCAG compliance
- [ ] The ui changes have visual elements which have been tested for WCAG compliance
- [ ] The ui changes have passed all checks for WCAG compliance

### Related WBS task

- [ ] Check here if the ui change is centered on the look and feel (https://github.com/NIAID-Data-Ecosystem/nde-roadmap/issues/52)
- [ ] Check here if the ui change includes new features (https://github.com/NIAID-Data-Ecosystem/nde-roadmap/issues/53)
- [X] Check here if the ui change was suggested by the NIAID team (https://github.com/NIAID-Data-Ecosystem/nde-roadmap/issues/2)

### For internal use only. Assignee, please select the status of this issue

- [ ] Not yet started
- [x] In progress
- [ ] Blocked
- [ ] Will not address

### UI change status check list

- [ ] This ui change has yet to be discussed between NIAID, Scripps, Leidos
- [X] This ui change has been discussed/reported between NIAID, Scripps, Leidos
- [X] This ui change has been mocked up
- [x] This ui change has been implemented on Dev
- [ ] This ui change has been approved for Staging
- [x] This ui change has been implemented on Staging
- [x] This ui change has been approved for Production
- [x] This ui change has been implemented on Production

**Comment by candicecz** [comment]
This change is implemented and viewable on staging:
![image](https://github.com/NIAID-Data-Ecosystem/nde-portal/assets/25373313/6ad20286-b9fc-4f9a-b040-7a977e851b44)

**Comment by gtsueng** [comment]
This is a barely-noticeable change. Based on their comment on this other barely noticeable change: https://github.com/NIAID-Data-Ecosystem/nde-portal/issues/209
![image](https://github.com/NIAID-Data-Ecosystem/nde-portal/assets/9200138/8ab61510-63e6-4885-95f9-301b591aefa1)

Go ahead and move this to production

**Comment by gtsueng** [comment]
The status of this issue has been changed to pending close out. The issue will be closed if no further changes are requested within a week.
