### ISSUE TITLE
[User Interface: Redesign]: Update description of Qiita

### ISSUE THREAD

**Issue by gtsueng** [NIAID-Data-Ecosystem/nde-portal#220]
### Issue Name

Update description of Qiita on landing page

### Issue Description

Per the request from the NIAID team, the description for Qiita should say: “Qiita is a repository that includes microbiome data and analysis tools.”

Note this change does not require any further approvals and can go straight through to production.

### Issue Discussion

The request was made via an email dated 2024.02.05

### WCAG Compliance Check

- [X] The ui changes are not expected to significantly affect WCAG compliance (ex- wording changes)
- [ ] The ui changes have visual elements which have yet to be tested for WCAG compliance
- [ ] The ui changes have visual elements which have been tested for WCAG compliance
- [ ] The ui changes have passed all checks for WCAG compliance

### Related WBS task

- [ ] Check here if the ui change is centered on the look and feel (https://github.com/NIAID-Data-Ecosystem/nde-roadmap/issues/52)
- [ ] Check here if the ui change includes new features (https://github.com/NIAID-Data-Ecosystem/nde-roadmap/issues/53)
- [X] Check here if the ui change was suggested by the NIAID team (https://github.com/NIAID-Data-Ecosystem/nde-roadmap/issues/2)

### For internal use only. Assignee, please select the status of this issue

- [ ] Not yet started
- [ ] In progress
- [ ] Blocked
- [ ] Will not address

### UI change status check list

- [ ] This ui change has yet to be discussed between NIAID, Scripps, Leidos
- [X] This ui change has been discussed/reported between NIAID, Scripps, Leidos
- [ ] This ui change has been mocked up
- [ ] This ui change has been implemented on Dev
- [ ] This ui change has been approved for Staging
- [ ] This ui change has been implemented on Staging
- [X] This ui change has been approved for Production
- [ ] This ui change has been implemented on Production

**Comment by rshabman** [comment]
Quick note: Can the team change the text for Qiita to: “Qiita is a repository that includes microbiome data and analysis tools.”  From what I can tell, its NIH supported (but not directly NIAID) and also supported by DoD. Thanks!  And we will look into this further.

**Comment by gtsueng** [comment]
@rshabman @sudvenk this is done. We have marked it as `pending closeout` and will close it in a week, if there are no further changes are suggested. You may close this issue if you'd like.

**Comment by gtsueng** [comment]
This issue has been pending closeout for a week. We are closing it as completed.
