### ISSUE TITLE
[User Interface: Redesign]: Create Repository-Level Metadata Compatibility Scores

### ISSUE THREAD

**Issue by gtsueng** [NIAID-Data-Ecosystem/nde-portal#221]
### Issue Name

Create Repository-Level Metadata Compatibility Scores

### Issue Description

This request arose from discussions around: https://github.com/NIAID-Data-Ecosystem/niaid-feedback/issues/115

To summarize: A repository owner found the metadata badges to be interesting, but was wondering about the fields they were missing. This led the NIAID team to create an issue suggesting that the legend for the record-level Metadata Completeness Badges be revised to potentially be more informative (e.g. - include missing fields).

Upon investigation of their request, we determined that this could potentially be discouraging to users who submit data to repositories we ingest as the missing fields might be due to repository limitations. Instead of altering the legend to include missing fields at the record-level, we recommend creating Repository-level metadata compatibility scores to indicate how compatible a repository's metadata is with the NIAID Data Ecosystem.

To do:
- [x] @DylanWelzel to generate repository-level scores: https://github.com/NIAID-Data-Ecosystem/nde-crawlers/issues/125
- [x] @candicecz to repurpose the metadata completeness badge to reflect the repository-level scores. Note, it's unclear where this badge will live (potentially the sources page) https://github.com/NIAID-Data-Ecosystem/nde-portal/issues/227
- [x] @EmilyHaag to generate the documentation page for the repository-level metadata compatibility badges

### Issue Discussion

This issue was discussed in the bi-weekly meeting dated 2024.01.30

### WCAG Compliance Check

- [ ] The ui changes are not expected to significantly affect WCAG compliance (ex- wording changes)
- [ ] The ui changes have visual elements which have yet to be tested for WCAG compliance
- [X] The ui changes have visual elements which have been tested for WCAG compliance
- [ ] The ui changes have passed all checks for WCAG compliance

### Related WBS task

- [ ] Check here if the ui change is centered on the look and feel (https://github.com/NIAID-Data-Ecosystem/nde-roadmap/issues/52)
- [X] Check here if the ui change includes new features (https://github.com/NIAID-Data-Ecosystem/nde-roadmap/issues/53)
- [ ] Check here if the ui change was suggested by the NIAID team (https://github.com/NIAID-Data-Ecosystem/nde-roadmap/issues/2)

### For internal use only. Assignee, please select the status of this issue

- [ ] Not yet started
- [ ] In progress
- [ ] Blocked
- [ ] Will not address

### UI change status check list

- [ ] This ui change has yet to be discussed between NIAID, Scripps, Leidos
- [X] This ui change has been discussed/reported between NIAID, Scripps, Leidos
- [x] This ui change has been mocked up
- [x] This ui change has been implemented on Dev
- [x] This ui change has been approved for Staging
- [x] This ui change has been implemented on Staging
- [x] This ui change has been approved for Production
- [x] This ui change has been implemented on Production

**Comment by gtsueng** [comment]
The repository-level scoring data was generated and @candicecz is working on creating visualizations of the data

**Comment by gtsueng** [comment]
All parts necessary for this badge are in Production. I am marking this issue as `pending close out` and will close it after a week if there are no further changes to be made.
