### ISSUE TITLE
[User Interface: Redesign]: Adjust Metadata Completeness badges for the ResourceCatalogs

### ISSUE THREAD

**Issue by gtsueng** [NIAID-Data-Ecosystem/nde-portal#222]
### Issue Name

Adjust Metadata Completeness badges for the ResourceCatalogs

### Issue Description

These have a different number of `required` and `recommended` fields than the Datasets, so the scores and badges may need to be adjusted accordingly (the alt legend as well)

To do:
- [x] @gtsueng to update the example metadata records to include the new fields `hasDownload` and `hasAPI`
- [x] Once metadata records have been updated in the DDE, @jal347 to update the DDE parser, ES mappings for these two fields, and the Data in Staging
- [x] Once the data has been updated in Staging, @candicecz to update the UI (can go to Staging)

#### Related Issues
https://github.com/NIAID-Data-Ecosystem/nde-crawlers/issues/117

### WCAG Compliance Check

- [X] The ui changes are not expected to significantly affect WCAG compliance (ex- wording changes)
- [ ] The ui changes have visual elements which have yet to be tested for WCAG compliance
- [ ] The ui changes have visual elements which have been tested for WCAG compliance
- [ ] The ui changes have passed all checks for WCAG compliance

### Related WBS task

- [ ] Check here if the ui change is centered on the look and feel (https://github.com/NIAID-Data-Ecosystem/nde-roadmap/issues/52)
- [X] Check here if the ui change includes new features (https://github.com/NIAID-Data-Ecosystem/nde-roadmap/issues/53)
- [ ] Check here if the ui change was suggested by the NIAID team (https://github.com/NIAID-Data-Ecosystem/nde-roadmap/issues/2)

### For internal use only. Assignee, please select the status of this issue

- [ ] Not yet started
- [x] In progress
- [ ] Blocked
- [ ] Will not address

### UI change status check list

- [X] This ui change has yet to be discussed between NIAID, Scripps, Leidos
- [ ] This ui change has been discussed/reported between NIAID, Scripps, Leidos
- [ ] This ui change has been mocked up
- [ ] This ui change has been implemented on Dev
- [X] This ui change has been approved for Staging
- [x] This ui change has been implemented on Staging
- [ ] This ui change has been approved for Production
- [ ] This ui change has been implemented on Production

**Comment by gtsueng** [comment]
This fix has been implemented on production and will be visible once a few ResourceCatalogs are added to production. We are marking this issue as `pending close out` and will close it after a week if there are no additional concerns surrounding this issue.
