### ISSUE TITLE
[User Interface: Redesign]: Download functions not working

### ISSUE THREAD

**Issue by gtsueng** [NIAID-Data-Ecosystem/nde-portal#223]
### Issue Name

Download functions not working

### Issue Description

Tested in Chrome by Nichollette and in Firefox by myself. The record-level download for JSON metadata downloads an empty JSON file. The download csv function just hangs indefinitely:
![image](https://github.com/NIAID-Data-Ecosystem/nde-portal/assets/9200138/431cbf07-9fd2-4447-a661-379250bafc42)

### WCAG Compliance Check

- [X] The ui changes are not expected to significantly affect WCAG compliance (ex- wording changes)
- [ ] The ui changes have visual elements which have yet to be tested for WCAG compliance
- [ ] The ui changes have visual elements which have been tested for WCAG compliance
- [ ] The ui changes have passed all checks for WCAG compliance

### Related WBS task

- [X] Check here if the ui change is centered on the look and feel (https://github.com/NIAID-Data-Ecosystem/nde-roadmap/issues/52)
- [ ] Check here if the ui change includes new features (https://github.com/NIAID-Data-Ecosystem/nde-roadmap/issues/53)
- [ ] Check here if the ui change was suggested by the NIAID team (https://github.com/NIAID-Data-Ecosystem/nde-roadmap/issues/2)

### For internal use only. Assignee, please select the status of this issue

- [ ] Not yet started
- [X] In progress
- [ ] Blocked
- [ ] Will not address

### UI change status check list

- [X] This ui change has yet to be discussed between NIAID, Scripps, Leidos
- [ ] This ui change has been discussed/reported between NIAID, Scripps, Leidos
- [ ] This ui change has been mocked up
- [ ] This ui change has been implemented on Dev
- [X] This ui change has been approved for Staging
- [ ] This ui change has been implemented on Staging
- [X] This ui change has been approved for Production
- [ ] This ui change has been implemented on Production
