### ISSUE TITLE
[User Interface: Redesign]: Advanced search default options

### ISSUE THREAD

**Issue by gtsueng** [NIAID-Data-Ecosystem/nde-portal#226]
### Issue Name

Advanced search default options

### Issue Description

The drop down selection options in the Advanced Search menu were previously developed using Laura's curated[ list of the fields](https://docs.google.com/spreadsheets/d/1YoCzJ85px-wuOEgOvz-XlVICIqataBwimLuUE4-eV2s/edit#gid=291523994) based on counts and usefulness. Since we've added many properties since then, it might be a good time to re-evaluate if we want to add any to the select drop down. @candicecz  generated a list of the fields we are currently missing. We need to review this list to determine if any new fields should be added to the advanced search.

This UI change is expected to be primarily imperceptible to the majority of casual users. Only users of the advanced search may notice the improvement in the options available in the drop down for the advanced search page.

This change may include fields from the Resource Catalog schema, for this reason, its movement through the development process will depend on the following issue: 
* https://github.com/orgs/NIAID-Data-Ecosystem/projects/6/views/6?pane=issue&itemId=52556325
* https://github.com/orgs/NIAID-Data-Ecosystem/projects/6/views/2?pane=issue&itemId=51825529

To do:
- [ ] @candicecz to generate the updated list of fields for consideration
- [ ] @gtsueng to review the list and make suggestions/recommendations
- [ ] @candicecz to implement any changes/updates

### Issue Discussion

This issue has not been discussed between NIAID, LEIDOS, and Scripps

### Mockup URL

https://docs.google.com/spreadsheets/d/1YoCzJ85px-wuOEgOvz-XlVICIqataBwimLuUE4-eV2s/edit#gid=291523994

### WCAG Compliance Check

- [X] The ui changes are not expected to significantly affect WCAG compliance (ex- wording changes)
- [ ] The ui changes have visual elements which have yet to be tested for WCAG compliance
- [ ] The ui changes have visual elements which have been tested for WCAG compliance
- [ ] The ui changes have passed all checks for WCAG compliance

### Related WBS task

- [ ] Check here if the ui change is centered on the look and feel (https://github.com/NIAID-Data-Ecosystem/nde-roadmap/issues/52)
- [X] Check here if the ui change includes new features (https://github.com/NIAID-Data-Ecosystem/nde-roadmap/issues/53)
- [ ] Check here if the ui change was suggested by the NIAID team (https://github.com/NIAID-Data-Ecosystem/nde-roadmap/issues/2)

### For internal use only. Assignee, please select the status of this issue

- [ ] Not yet started
- [X] In progress
- [ ] Blocked
- [ ] Will not address

### UI change status check list

- [X] This ui change has yet to be discussed between NIAID, Scripps, Leidos
- [ ] This ui change has been discussed/reported between NIAID, Scripps, Leidos
- [ ] This ui change has been mocked up
- [ ] This ui change has been implemented on Dev
- [ ] This ui change has been approved for Staging
- [ ] This ui change has been implemented on Staging
- [ ] This ui change has been approved for Production
- [ ] This ui change has been implemented on Production
