### ISSUE TITLE
[User Interface: Redesign]: Repository-level Metadata Compatibility badges

### ISSUE THREAD

**Issue by gtsueng** [NIAID-Data-Ecosystem/nde-portal#227]
### Issue Name

Repository-level Metadata Compatibility badges

### Issue Description

According to the NIAID team, a repository owner was excited about the Metadata Completeness badge, but lamented that it was not informative enough. This prompted the NIAID team to request improvements to the legend for the metadata completeness badge suggesting the inclusion of missing fields. Since missing fields can be repository-limited, it makes more sense for this sort of information to be provided at the repository level. Towards that end, we will create a repository-level metadata compatibility badge which will help visualize how compatible repositories are with the metadata ingested by the NIAID Data Ecosystem.

Note, this issue is for the design of the badge only. Where the badge will be displayed has yet to be discussed. Potential locations include the sources page, and the 'featured pages' which have yet to be developed.

### Dependencies
The data needed for this issue will be discussed in the following GH Ticket: 
https://github.com/orgs/NIAID-Data-Ecosystem/projects/6/views/2?pane=issue&itemId=53297771

### Issue Discussion

The history of this ticket can be sourced to this issue: https://github.com/orgs/NIAID-Data-Ecosystem/projects/6/views/5?pane=issue&itemId=50899235

### Mockup URL

https://nde-dev.biothings.io/compatibility

### WCAG Compliance Check

- [ ] The ui changes are not expected to significantly affect WCAG compliance (ex- wording changes)
- [ ] The ui changes have visual elements which have yet to be tested for WCAG compliance
- [x] The ui changes have visual elements which have been tested for WCAG compliance
- [ ] The ui changes have passed all checks for WCAG compliance

### Related WBS task

- [ ] Check here if the ui change is centered on the look and feel (https://github.com/NIAID-Data-Ecosystem/nde-roadmap/issues/52)
- [X] Check here if the ui change includes new features (https://github.com/NIAID-Data-Ecosystem/nde-roadmap/issues/53)
- [ ] Check here if the ui change was suggested by the NIAID team (https://github.com/NIAID-Data-Ecosystem/nde-roadmap/issues/2)

### For internal use only. Assignee, please select the status of this issue

- [ ] Not yet started
- [ ] In progress
- [ ] Blocked
- [ ] Will not address

### UI change status check list

- [ ] This ui change has yet to be discussed between NIAID, Scripps, Leidos
- [X] This ui change has been discussed/reported between NIAID, Scripps, Leidos
- [x] This ui change has been mocked up
- [ ] This ui change has been implemented on Dev
- [ ] This ui change has been approved for Staging
- [ ] This ui change has been implemented on Staging
- [ ] This ui change has been approved for Production
- [ ] This ui change has been implemented on Production

**Comment by gtsueng** [comment]
@rshabman @sudvenk @lisa-mml @hartwickma we have a few potential designs for the **repository-level** metadata compatibility badge which can be found at: https://nde-dev.biothings.io/compatibility

An initial draft of the documentation for the **repository-level** metadata compatibility badge can be found at: https://docs.google.com/document/d/1Q1_S3x239slpAhMpOnNTJKLzdc9ik7Up4H6Dty-U7xs/edit?pli=1 . This draft is expected to be updated with images that explain the badge, once a badge type has been selected.

We are changing the status of this issue to `Review requested-deliverable` and would like to include this in the agenda for the biweekly discussion on 2024.04.16 with OCGR.

**Comment by gtsueng** [comment]
Per the discussion on 2024.06.11, the preferred badge is the bar badge; with the following suggested changes:
1. Rather than using value-based coverage which depends on % coverage of metadata in the repo, and can be harder to interpret with all the different shades of pink/purple, provide a simple indicator of is it available or not
2. Remove the % coverage from the hover info, since there will not be shades of color to reflect % coverage
3. The % coverage information is interesting, so leave it in the metadata as we may want to revisit this matter at another time, but remove it from the badge
4. The order of all metadata fields in the badge should be kept consistent between the repositories to allow users to quickly evaluate if a repository collects certain metadata
5. The metadata compatibility documentation should be updated to reflect a positional changes from a way for seeing the coverage of metadata in each repository as a potential indicator as to whether the repository allows for metadata (in case a user is looking for a place to deposit their dataset)

@rshabman @sudvenk @lisa-mml @hartwickma we will focus on updating the bar chart mock up to reflect suggestions 1-4. We will update the documentation for the repository-level badge based on suggestion 5.

**Comment by gtsueng** [comment]
@rshabman @sudvenk @lisa-mml @hartwickma The bar chart/grid plot hybrid has been updated to reflect the requsted changes and can be viewed here: https://nde-dev.biothings.io/compatibility
 
If approved for implementation on Staging, these 'badges' would be added to the 'Sources' page

**Comment by hartwickma** [comment]
Hi @gtsueng thank you for providing the updated mockups, these look very nice. 

One of the requested updates:

_Remove the % coverage from the hover info, since there will not be shades of color to reflect % coverage_

but this information still appears in hover boxes, where in some cases, a solid box is at 86% (Date, Access Clinical Data) and DDE Fundamental shows all boxes filled but reports 97%. 

As discussed, please remove % from hovers and update percentages that appear next to the boxes as a static figure so that they represent a binary report of whether or not that meta data is collected collected/reported by the repositry. 

Please also provide a link to where the updated documentation can be found.

**Comment by gtsueng** [comment]
@candicecz please update the hover text such that:
* If NOT augmented AND:
  * If percentage>0: "`<field name>` metadata is collected and available for this source."
  * If percentage=0: "`<field name>` metadata was not found for this source"
* If augmented AND:
  * percentage > 0: "`<field name>` metadata is collected and available for this source. <field name> was also augmented for this source."
  * percentage = 0: "`<field name>` metadata was not found for this source, but was augmented for this source."

**Comment by gtsueng** [comment]
@hartwickma @rshabman @lisa-mml @sudvenk

The badge has been updated and can be viewed here: https://nde-dev.biothings.io/compatibility

The Ask: We seek permission to add the badge to Staging

**Comment by hartwickma** [comment]
Hi @gtsueng, thank you for this update. Unless there is substantial change or concern, please move towards production. NIAID does not need to review in between steps.

**Comment by gtsueng** [comment]
@hartwickma @lisa-mml @rshabman @sudvenk

The repository-level metadata compatibility badges are now live [on production](https://data.niaid.nih.gov/sources)

I am marking this issue as `pending close out` and will close it after a week if there are no further changes to be made.
