### ISSUE TITLE
[User Interface: Redesign]: Display of Resource Catalogs on landing page

### ISSUE THREAD

**Issue by gtsueng** [NIAID-Data-Ecosystem/nde-portal#229]
### Issue Name

Display of Resource Catalogs on landing page

### Issue Description

The NIAID team would like the Resource Catalogs displayed on the landing page, but are concerned that the distribution of the different resources across different tabs will cause them to be hidden. For this reason, they've suggested having a single table with additional facets in order to be able to do some sorting.

Specifically consider re-designing the landing page such that:
> There are fewer tabs--Too many tabs is confusing. Consider merging the tables in the two tabs on the landing page into one table so that it can serve as an additional navigational element. Potentially add key columns such as:
> * conditionsOfAccess
> * IID vs Generalist
> * number of ingested records (Indirect way to show if it's fully integrated or just a record) <-- Or any other way of distinguishing between Resource Catalog and a fully integrated resource.

To do: 
- [x] @candicecz Generate mock ups for an improved landing page
- [x] @DylanWelzel add `conditionsOfAccess` field to repository-level metadata:
     * The value should be set such that:
       *If 100% of the records for a repository have the same value, `conditionsOfAccess` = that value
       *If records for a repository have mixes of different values, `conditionsOfAccess` = `Varied`
       *If 100% of the records for a repository are missing a value for this field, `conditionsOfAccess` = `Unknown` (at least until we can figure it out and fix it
- [x] @gtsueng Get feedback from NIAID team and seek approval before moving this change to staging

### Issue Discussion

This issue was discussed at the ODSET onsite meeting on 2024.03.05

### Mockup URL
https://drive.google.com/file/d/14wpF4wshsFd5Bv6_EjRpMVNVizk1eiCO/view

### WCAG Compliance Check

- [ ] The ui changes are not expected to significantly affect WCAG compliance (ex- wording changes)
- [ ] The ui changes have visual elements which have yet to be tested for WCAG compliance
- [x] The ui changes have visual elements which have been tested for WCAG compliance
- [ ] The ui changes have passed all checks for WCAG compliance

### Related WBS task

- [ ] Check here if the ui change is centered on the look and feel (https://github.com/NIAID-Data-Ecosystem/nde-roadmap/issues/52)
- [ ] Check here if the ui change includes new features (https://github.com/NIAID-Data-Ecosystem/nde-roadmap/issues/53)
- [X] Check here if the ui change was suggested by the NIAID team (https://github.com/NIAID-Data-Ecosystem/nde-roadmap/issues/2)

### For internal use only. Assignee, please select the status of this issue

- [ ] Not yet started
- [x] In progress
- [ ] Blocked
- [ ] Will not address

### UI change status check list

- [ ] This ui change has yet to be discussed between NIAID, Scripps, Leidos
- [X] This ui change has been discussed/reported between NIAID, Scripps, Leidos
- [x] This ui change has been mocked up
- [ ] This ui change has been implemented on Dev
- [x] This ui change has been approved for Staging
- [ ] This ui change has been implemented on Staging
- [ ] This ui change has been approved for Production
- [ ] This ui change has been implemented on Production

**Comment by gtsueng** [comment]
The mock ups are available as of 2024.03.12 and a few issues should be considered regardless of the design:
1. Obtaining approval to use logos for 200+ repositories may be time consuming.
    * A potential work around is to use one icon for all Resource Catalog entries, or an icon for each Collection Type
2. Consider changing the wording from `Currently Included Repositories` to `Currently Included Resources` or `Currently Included Resource Catalogs` since repositories may be considered a type of resource or resource catalog, but a resource catalog is not necessarily a repository.
3. Consider changing the wording of `Repository` to `Dataset Repository` for the repositories for which we have ingested data. The reason is that these are Dataset repositories. There are other types of repositories (Code, Software, etc.) for which records cannot be ingested at this time (and will be ingested as Resource Catalogs)
4. Currently, `conditionsOfAccess` for ingested records are set at the dataset record level and are not available at the repository level. To do:
   - [ ] Investigate how to best make this field accessible at the repository level for integrated repositories
5. In order for the short, formula-based description for each resource catalog to be available, we need to ensure that the following information is available in Lisa's spreadsheet (additional columns): 
    * funder
    * repository type (generalist, IID, etc.)
    * Data type
 
The ask: Please review the [mock ups](https://drive.google.com/file/d/14wpF4wshsFd5Bv6_EjRpMVNVizk1eiCO/view) and provide any feedback or suggestions for improving them or any feedback/suggestions for addressing the design issues (1-5) mentioned above. Once one of the mock up options are selected and approved to move forward, we will implement the mock up (option 1 or option 2) to Staging.

**Comment by gtsueng** [comment]
Per Scripps internal discussions on 2024.03.13, an additional, simplified option will be added to the mockups. The mockups will be an agenda item for the biweekly meeting dated 2024.03.19

**Comment by gtsueng** [comment]
Following the biweekly meeting dated 2024.03.19, we are changing the status of this issue to `Review requested - deliverable` and seeking feedback on the mock ups. If at least one of the mock ups is satisfactory, we would be happy to move that one to staging. Otherwise, we can improve the mock ups based on the feedback from the NIAID team (after NIAID internal discussions)

We have created a check list which details the features in this mock up. If desired, it can be used in the review of the mock ups. 
https://docs.google.com/document/d/1R945Tasg0BTOaXFtjKUNmeqW8eOPeFbeVH0EjqaevGE/edit?usp=sharing

**Comment by rshabman** [comment]
Thanks for the mockups!  Below is feedback from our first review.  Note, we would like to see a modification of Option 1.  We will also share with OCGR for their feedback, both the current options and the requested modification.  If anything is unclear please let us know.

**On initial review NIAID likes Option 1:  each piece of information about the resource has its own column and we suggest some additional modifications. Could you modify Option 1?** 
  
- Each type of data could be a different column.   
- IID/generalist = 1 column;   
- repository/resource catalog = 1 column;  
- access =1 column.  

With this format you would not need tabs 
 
**Comments on options 2 &3** 
Both options have different types of information in the same columns, which may be difficult for the user.  

**Other comments:** 
- Ensure there are straightforward definitions in documentation each of the Types.  Also include a definition for “Type” and why multiple types are assigned in some cases.   
- Include a definition for “Access” and how “Access” was evaluated. Be careful when describing “access”.  Consider an “Unknown” category or confirm assumption about “access” with repo managers rather than incorrectly assigning.

**Comment by gtsueng** [comment]
Thanks for the feedback, @rshabman @sudvenk. @candicecz will create a revised mock up based on your feedback.

**Comment by gtsueng** [comment]
The revised mock up can be found here: https://drive.google.com/file/d/1U7lo-UIuC9v1SL0KAFXWpOsPRqbAN-7x/view?usp=drive_link
And a Lyssna study on the mock ups can be found here: https://github.com/orgs/NIAID-Data-Ecosystem/projects/6/views/2?pane=issue&itemId=58290925

**Comment by gtsueng** [comment]
With the expectation that this issue will be presented at the next bi-weekly meeting for discussion with OCGR, I am changing the status of this issue to `review requested - deliverable`

**Comment by gtsueng** [comment]
The OCGR feedback is now an agenda item for the bi-weekly meeting dated 2024.04.30

**Comment by gtsueng** [comment]
Per the discussion at the bi-weekly meeting dated 2024.04.30, the mock up has been revised to address the recommendations raised by OCGR, namely:
* Spelling out the access types
* Removal of the button-like appearances for tags
* Shading every other row in the table
* Removal of resource logos (note, these logos originally linked to the resource, so the removal of these logos also removes the link to the resource)
* Inclusion of the header "Explore all included resources"

![Image](https://github.com/NIAID-Data-Ecosystem/nde-portal/assets/9200138/482a9dc1-f380-49e1-abc6-8b6560701754)

**The Ask** We seek to move this mock up to staging

**Comment by gtsueng** [comment]
@candicecz this new mock up has been approved for staging

**Comment by candicecz** [comment]
Changes are now viewable on [staging](https://data-staging.niaid.nih.gov/)

**Comment by gtsueng** [comment]
@hartwickma @lisa-mml @rshabman @sudvenk

The improved landing page (with resource catalogs) is now on staging. We are changing the status of this issue to 'review requested - staging'

The Ask: We seek approval to move this landing page to Production

**Comment by gtsueng** [comment]
@hartwickma @lisa-mml @rshabman @sudvenk

Per the discussion on 2024.05.29 we are moving the design from staging to production. In parallel, we will run a [Lyssna test](https://github.com/NIAID-Data-Ecosystem/nde-portal/issues/243) to better understand user preference on the design (with our without additional columns) and whether or not the presence of filters will be confusing without the additional columns

**Comment by candicecz** [comment]
The current design for the landing page table is viewable on [production](https://data.niaid.nih.gov/)
![image](https://github.com/NIAID-Data-Ecosystem/nde-portal/assets/25373313/ae089aad-61f2-455d-954e-067311e52207)

**Comment by gtsueng** [comment]
Great! I am marking this issue as `in progress-refinement` while we await the results of the Lyssna study to inform on how to best move forward.

**Comment by gtsueng** [comment]
Hi @hartwickma, @rshabman, @sudvenk, @lisa-mml -- The results of the Lyssna study on the Landing page table can be found here: https://docs.google.com/presentation/d/1HAFuqGolPBYW4ixcjTeRkOdqnRvIvu_o/edit?usp=sharing&ouid=114065631315523104759&rtpof=true&sd=true

We look forward to discussing these results along with the additional feedback from OCGR during the biweekly meeting dated 2024.06.11

**Comment by gtsueng** [comment]
At the biweekly meeting dated 2024.06.11, OCGR provided their rationale for a mock up they created: https://drive.google.com/file/d/1_lzcfT2VCjdwch3r5D3DGAQ4sr-h68bV/view which included:
* Enhancing the findability of documentation and helpful information for using the site

While there was certainty that the image was purchased by NIAID for use, the NIAID ODSET and OCGR teams would confirm that the image could be used on the Discovery Portal, or potentially provide an alternative image which has been approved for use on the site.

**Comment by gtsueng** [comment]
At the biweekly meeting dated 2024.06.25, the NIAID team raised concerns about the current domain categorizations of the resources/sources on the site. Per [their comment](https://github.com/NIAID-Data-Ecosystem/nde-crawlers/issues/135#issuecomment-2192539730), 

> We also discussed a related item in the meeting yesterday about the new sub headers in the filter section, where new terms (Other Resources, Basic science Repositories). Please remove these terms and return to the previously agreed upon Domains of 'IID' and 'Generalist Repositories' while discussions continue about how best to make domain assignments and assign terms.

Note that the above change was explicitly about the new sub headers in the filter section. How this change will propagate to the landing page is not clear.

**Comment by hartwickma** [comment]
Thank you @gtsueng. We suggest to roll back and revert to the two domains (IID or generalist) so that the Portal is consistent in term usage throughout all pages.

**Comment by gtsueng** [comment]
@hartwickma @sudvenk @lisa-mml @rshabman 

As mentioned in the progress update email from 2024.06.20, Candice is out and we recommend freezing any front end changes on Production until she returns.
    * Note, rather than roll back, there are [additional landing page improvements to implement](https://drive.google.com/file/d/1_lzcfT2VCjdwch3r5D3DGAQ4sr-h68bV/view). If there is a **preferred pre-approved image asset that the NIAID team can provide to us**, we can have Candice implement both the (return to two categories, and the OCGR-recommended improvements to the landing page) as soon as she returns (2nd week of July)

In the mean time, we can update the metadata such that all resources categorized as non-IID in the excel spreadsheet that was provided to us, as generalist. These are back end changes which should appear automatically on the front end.

If this plan will adequately address your concerns, let us know and we will move forward with the implementation.

**Comment by hartwickma** [comment]
Hi @gtsueng, thank you for following up on this issue and for providing additional information. We have provided some clarification and suggestions for next steps:

1. The spreadsheet columns were not instructional for how to set up staging. We continue to explore the best way to represent resources on the portal and are interested to discuss approaches to add additional categorizations in a robust way. 

2. ODSET met with OCGR yesterday. We will send the landing page materials later today for discussion on our call on July 9th. 

3. Please proceed with the metadata update as proposed for the time being. We can explore these classifications at a later time.

**Comment by gtsueng** [comment]
Hi @hartwickma, @sudvenk

Acknowledged, we will proceed with the metadata updates

**Comment by gtsueng** [comment]
@hartwickma , @sudvenk,

The metadata has been updated such that it is either `IID` or `Generalist` on Production

**Comment by hartwickma** [comment]
Thank you for this update. Looks great!

**Comment by gtsueng** [comment]
I am marking this issue as `pending close out` and will close it after a week if there are no additional changes to be made regarding the landing page table. For OCGR recommendations on landing page improvements, see:
* https://github.com/NIAID-Data-Ecosystem/nde-portal/issues/253
