### ISSUE TITLE
[User Interface: Redesign]: Notice banner on landing page

### ISSUE THREAD

**Issue by gtsueng** [NIAID-Data-Ecosystem/nde-portal#233]
### Issue Name

Notice banner on landing page

### Issue Description

External repositories will occasionally be down for maintenance without any warning. When this happens, all of the links from records to the source repositories will transiently be broken. To ensure that users of the site understand that this issue is due to the original source being transiently down, rather than an issue on our end, it would be good if we could implement a STRAPI-based banner which would enable easy updates without taking additional dev time.

Expected banner behavior: If there is no text content for the banner in STRAPI, it will be invisible (alternatively, make it invisible if content is only draft (rather than published), and we can unpublish/revert-to-draft, any notice that has been posted

Expected banner appearance: The banner could potentially look like the notice about which API is being used as seen on Staging:
![image](https://github.com/NIAID-Data-Ecosystem/nde-portal/assets/9200138/dd754eec-050b-4ee4-81e4-d88a037d606a)

### Issue Discussion

The history of this issue can be found at: https://github.com/orgs/NIAID-Data-Ecosystem/projects/6/views/2?pane=issue&itemId=52453910

### WCAG Compliance Check

- [ ] The ui changes are not expected to significantly affect WCAG compliance (ex- wording changes)
- [X] The ui changes have visual elements which have yet to be tested for WCAG compliance
- [ ] The ui changes have visual elements which have been tested for WCAG compliance
- [ ] The ui changes have passed all checks for WCAG compliance

### Related WBS task

- [ ] Check here if the ui change is centered on the look and feel (https://github.com/NIAID-Data-Ecosystem/nde-roadmap/issues/52)
- [ ] Check here if the ui change includes new features (https://github.com/NIAID-Data-Ecosystem/nde-roadmap/issues/53)
- [X] Check here if the ui change was suggested by the NIAID team (https://github.com/NIAID-Data-Ecosystem/nde-roadmap/issues/2)

### For internal use only. Assignee, please select the status of this issue

- [ ] Not yet started
- [ ] In progress
- [ ] Blocked
- [ ] Will not address

### UI change status check list

- [ ] This ui change has yet to be discussed between NIAID, Scripps, Leidos
- [X] This ui change has been discussed/reported between NIAID, Scripps, Leidos
- [ ] This ui change has been mocked up
- [ ] This ui change has been implemented on Dev
- [ ] This ui change has been approved for Staging
- [ ] This ui change has been implemented on Staging
- [ ] This ui change has been approved for Production
- [ ] This ui change has been implemented on Production

**Comment by gtsueng** [comment]
This issue was raised at the bi-weekly meeting dated 2024.04.30.

**Comment by candicecz** [comment]
This is currently implemented in the staging and production instance.
Example screenshot: 
![image](https://github.com/NIAID-Data-Ecosystem/nde-portal/assets/25373313/d8cb98b9-95d5-4fdb-9d5e-1000c0232631)

**Comment by gtsueng** [comment]
Great!

@rshabman @sudvenk @hartwickma @lisa-mml, The sample warning banner (seen in the mock up above) will NOT appear unless someone provides some text via STRAPI. This banner will be used to notify users of transiently broken links due to external repository maintenance and the like. If you have feedback on the appearance of the banner (the one that says "This is a sample warning", please let us know, otherwise we would like to close this issue.

If you are concerned about the SOP for how and when this banner will be applied, we will open a separate ticket.

**Comment by hartwickma** [comment]
Thank you, please move to production and inform NIAID when the SOP is drafted.

**Comment by gtsueng** [comment]
Thanks, we will let you know when the SOP is drafted. The banner itself is already available on production and we are marking this issue as `pending close out` and will close it after a week, if there are no additional concerns regarding the banner itself.
