### ISSUE TITLE
[User Interface: Redesign]: Change 'view dataset' button for Resource Catalogs

### ISSUE THREAD

**Issue by gtsueng** [NIAID-Data-Ecosystem/nde-portal#234]
### Issue Name

Change 'view dataset' button for Resource Catalogs

### Issue Description

The 'view dataset' button seems inappropriate for Resource Catalogs. 
![image](https://github.com/NIAID-Data-Ecosystem/nde-portal/assets/9200138/1fec0c7a-db86-4db1-a84e-8db423b28be3)

There are two potential quick fixes:
1. Change to  'view record' 
  * Pro: Generally compatible with whatever type of record, Dataset, ResourceCatalog, anything else that might be added in the future
  * Con: Potentially confusing as we haven't really used the term anywhere else on the site
2. Change to {type}
  * Pro: Addresses problem, and is another opportunity to point out that this is of a different type than datast
  * Con: May need to be manually set again for other future types (but that's a problem for later).

### Issue Discussion

This issues has yet to be discussed

### Mockup URL

https://data-staging.niaid.nih.gov/search?q=TB+Portals

### WCAG Compliance Check

- [X] The ui changes are not expected to significantly affect WCAG compliance (ex- wording changes)
- [ ] The ui changes have visual elements which have yet to be tested for WCAG compliance
- [ ] The ui changes have visual elements which have been tested for WCAG compliance
- [ ] The ui changes have passed all checks for WCAG compliance

### Related WBS task

- [X] Check here if the ui change is centered on the look and feel (https://github.com/NIAID-Data-Ecosystem/nde-roadmap/issues/52)
- [ ] Check here if the ui change includes new features (https://github.com/NIAID-Data-Ecosystem/nde-roadmap/issues/53)
- [ ] Check here if the ui change was suggested by the NIAID team (https://github.com/NIAID-Data-Ecosystem/nde-roadmap/issues/2)

### For internal use only. Assignee, please select the status of this issue

- [ ] Not yet started
- [ ] In progress
- [ ] Blocked
- [ ] Will not address

### UI change status check list

- [X] This ui change has yet to be discussed between NIAID, Scripps, Leidos
- [ ] This ui change has been discussed/reported between NIAID, Scripps, Leidos
- [ ] This ui change has been mocked up
- [ ] This ui change has been implemented on Dev
- [X] This ui change has been approved for Staging
- [ ] This ui change has been implemented on Staging
- [ ] This ui change has been approved for Production
- [ ] This ui change has been implemented on Production

**Comment by gtsueng** [comment]
The [results of the terminology study](https://docs.google.com/presentation/d/1fqEkJYOlrF9iVCxzr8h75eSqItlwQuzG/edit#slide=id.g2d2197f6f51_0_3) indicate that `resource` is the preferred term for a record. Additionally, the use of `view resource` for resource catalogs will be consistent with the currently used url structure.

**Comment by candicecz** [comment]
'View dataset' has been changed to 'View resource' . It is now viewable in production.
![image](https://github.com/NIAID-Data-Ecosystem/nde-portal/assets/25373313/703e1a2f-215f-4390-b7f6-36945e6a6df0)

**Comment by gtsueng** [comment]
We are marking this issue as `pending close out` and will close it after a week if there are no more comments or concerns regarding this issue.
