### ISSUE TITLE
[User Interface: Redesign]: Display link to resource ('identifier; field) for ResourceCatalog

### ISSUE THREAD

**Issue by gtsueng** [NIAID-Data-Ecosystem/nde-portal#237]
### Issue Name

Display link to resource ('identifier' field) for ResourceCatalog

### Issue Description

Currently, all ResourceCatalog are being ingested via the DDE. This means that the metadata is coming from the DDE so all the related 'access' buttons link to either the DDE or a portal on the DDE. This behavior will likely be unsatisfactory to resource providers, who would rather send users to their own sites.

For each ResourceCatalog, the canonical url for the ResourceCatalog is still stored in the `identifier` field, so we could potentially use that (not recommended) to send people to the actual resource since the DDE will not.

For ResourceCatalogs ingested from the DDE (and NOT datasets ingested from the DDE):
- [x] Update the DDE parser to save the original url in the `url` field (@DylanWelzel)
  - [x] store the link to the DDE record in the `sdPublisher.url` field
  - [ ] fix the parsing of the topicCategory field such that the format matches that of other augmented fields (like species, infectiousAgent, etc.) 

### WCAG Compliance Check

- [ ] The ui changes are not expected to significantly affect WCAG compliance (ex- wording changes)
- [X] The ui changes have visual elements which have yet to be tested for WCAG compliance
- [ ] The ui changes have visual elements which have been tested for WCAG compliance
- [ ] The ui changes have passed all checks for WCAG compliance

### Related WBS task

- [X] Check here if the ui change is centered on the look and feel (https://github.com/NIAID-Data-Ecosystem/nde-roadmap/issues/52)
- [ ] Check here if the ui change includes new features (https://github.com/NIAID-Data-Ecosystem/nde-roadmap/issues/53)
- [ ] Check here if the ui change was suggested by the NIAID team (https://github.com/NIAID-Data-Ecosystem/nde-roadmap/issues/2)

### For internal use only. Assignee, please select the status of this issue

- [ ] Not yet started
- [ ] In progress
- [ ] Blocked
- [ ] Will not address

### UI change status check list

- [ ] This ui change has yet to be discussed between NIAID, Scripps, Leidos
- [x] This ui change has been discussed/reported between NIAID, Scripps, Leidos
- [ ] This ui change has been mocked up
- [ ] This ui change has been implemented on Dev
- [ ] This ui change has been approved for Staging
- [ ] This ui change has been implemented on Staging
- [ ] This ui change has been approved for Production
- [ ] This ui change has been implemented on Production

**Comment by gtsueng** [comment]
@DylanWelzel once you fix the parser to save the original urls for ResourceCatalogs, please create a new build of the DDE for staging. The context-less Dataset records ingested from the NIAID Sysbio portal from the DDE have been fixed, so the data should reflect that change.

**Comment by gtsueng** [comment]
The linking of a ResourceCatalog record to the actual resource rather than to the DDE entry of the record was requested in an email dated 2024.05.07

**Comment by gtsueng** [comment]
I am marking this issue as `pending close out` and will close this issue after a week if there are no additional comments or concerns. The display of `topicCategory` information is already in its own issue.
