### ISSUE TITLE
[User Interface: Redesign]: Remove display of collectionType from ResourceCatalog card header

### ISSUE THREAD

**Issue by gtsueng** [NIAID-Data-Ecosystem/nde-portal#239]
### Issue Name

Remove display of collectionType from ResourceCatalog card header

### Issue Description

The NIAID team has requested that the display of the 'collectionType' be removed from the ResourceCatalog card header
![image](https://github.com/NIAID-Data-Ecosystem/nde-portal/assets/9200138/3e3146f9-fa97-428e-a4f8-5cd6ba477748)

### Issue Discussion

The request was made via an email dated 2024.05.07 from @sudvenk on behalf of the NIAID team

### WCAG Compliance Check

- [X] The ui changes are not expected to significantly affect WCAG compliance (ex- wording changes)
- [ ] The ui changes have visual elements which have yet to be tested for WCAG compliance
- [ ] The ui changes have visual elements which have been tested for WCAG compliance
- [ ] The ui changes have passed all checks for WCAG compliance

### Related WBS task

- [ ] Check here if the ui change is centered on the look and feel (https://github.com/NIAID-Data-Ecosystem/nde-roadmap/issues/52)
- [ ] Check here if the ui change includes new features (https://github.com/NIAID-Data-Ecosystem/nde-roadmap/issues/53)
- [X] Check here if the ui change was suggested by the NIAID team (https://github.com/NIAID-Data-Ecosystem/nde-roadmap/issues/2)

### For internal use only. Assignee, please select the status of this issue

- [ ] Not yet started
- [ ] In progress
- [ ] Blocked
- [ ] Will not address

### UI change status check list

- [ ] This ui change has yet to be discussed between NIAID, Scripps, Leidos
- [X] This ui change has been discussed/reported between NIAID, Scripps, Leidos
- [ ] This ui change has been mocked up
- [ ] This ui change has been implemented on Dev
- [X] This ui change has been approved for Staging
- [ ] This ui change has been implemented on Staging
- [X] This ui change has been approved for Production
- [ ] This ui change has been implemented on Production

**Comment by gtsueng** [comment]
This is now on production. We are marking this as `pending close out` and will close this issue in a week if there are no further comments or concerns
