### ISSUE TITLE
[User Interface: Redesign]: Computational Tool focused view (with comptool-focused facets and filters)

### ISSUE THREAD

**Issue by gtsueng** [NIAID-Data-Ecosystem/nde-portal#241]
### Issue Name

Computational Tool focused view (with comptool-focused facets and filters)

### Issue Description

The current facets and filters are based on metadata that's available for Datasets. ComputationalTools are likely to be faceted and filtered on more computational-tool specific facets and filters, so we should consider editing the default facets and filters if the "Type" selected is computational tool

### Issue Discussion

This issue was raised at the bi-weekly meeting dated 2024.05.28

### WCAG Compliance Check

- [ ] The ui changes are not expected to significantly affect WCAG compliance (ex- wording changes)
- [X] The ui changes have visual elements which have yet to be tested for WCAG compliance
- [ ] The ui changes have visual elements which have been tested for WCAG compliance
- [ ] The ui changes have passed all checks for WCAG compliance

### Related WBS task

- [ ] Check here if the ui change is centered on the look and feel (https://github.com/NIAID-Data-Ecosystem/nde-roadmap/issues/52)
- [X] Check here if the ui change includes new features (https://github.com/NIAID-Data-Ecosystem/nde-roadmap/issues/53)
- [ ] Check here if the ui change was suggested by the NIAID team (https://github.com/NIAID-Data-Ecosystem/nde-roadmap/issues/2)

### For internal use only. Assignee, please select the status of this issue

- [ ] Not yet started
- [ ] In progress
- [ ] Blocked
- [ ] Will not address

### UI change status check list

- [ ] This ui change has yet to be discussed between NIAID, Scripps, Leidos
- [X] This ui change has been discussed/reported between NIAID, Scripps, Leidos
- [ ] This ui change has been mocked up
- [ ] This ui change has been implemented on Dev
- [ ] This ui change has been approved for Staging
- [ ] This ui change has been implemented on Staging
- [ ] This ui change has been approved for Production
- [ ] This ui change has been implemented on Production

**Comment by gtsueng** [comment]
For CompTool-specific filters that would be useful, I recommend focusing on the records from the bio.tools repository as bio.tools has more software-related metadata fields filled out than other repositories

**Comment by gtsueng** [comment]
The ComputationalTool-related UI changes are now on Staging awaiting approval for Production. This includes updates for:
* the [cards](https://github.com/NIAID-Data-Ecosystem/nde-portal/issues/240) 
* the [resources page](https://github.com/NIAID-Data-Ecosystem/nde-portal/issues/267)
* the [landing page search options](https://github.com/NIAID-Data-Ecosystem/nde-portal/issues/242)

The following updates cannot be applied to staging (due to the STRAPI pages already being published), so the updates will need to be approved in google docs before moving to production:
* the [documentation](https://github.com/NIAID-Data-Ecosystem/nde-portal/issues/268)

The following changes are under investigation:
* Facets and filter updates (this issue)

**Comment by gtsueng** [comment]
The ComputationalTool-related UI changes are on Production. This includes updates for:

* the https://github.com/NIAID-Data-Ecosystem/nde-portal/issues/240
* the https://github.com/NIAID-Data-Ecosystem/nde-portal/issues/267
* the https://github.com/NIAID-Data-Ecosystem/nde-portal/issues/242
*  the https://github.com/NIAID-Data-Ecosystem/nde-portal/issues/268

The following changes are under investigation:
* Facets and filter updates (this issue)

**Comment by gtsueng** [comment]
@hartwickma, @rshabman, @lisa-mml, @sudvenk,

With the addition of the ComputationalTools to the site, the filters on the search result page can get very messy since there are filters that only apply to Datasets/ResourceCatalogs and filters that only apply to ComputationalTools. 

We have generated a few mock-ups to address the issue of potentially messy filters (one of which includes the Visual summary as an overview page), and would like to get your opinion on the best design to move forward. If possible, we would love to discuss this at the bi-weekly meeting dated 2025.01.21. In preparation for that discussion, here are the potential designs and their expected pros and cons:

1. [Design 1](https://drive.google.com/file/d/1nnwTdnab-D5TABlnlyzQ6tOBdSrIChAl/view?usp=drive_link) - This design splits the search results into 4 tabs: `Any Type`, `Resource Catalog`, `Dataset`, and `Computational Tool`. Each Type-specific tab would display only the relevant type-specific filters on the left hand side, and only records of that specific type in the record list. 
  * Pros: 
    * Searching for a specific type will default the user to the tab with the relevant results; however, they will be able to explore relevant results of a different type, by simply clicking on a different tab.
    * Resource Catalogs are in their own tab, so users do not need to scroll through all the Resource catalogs just to see relevant datasets. 
      * Resource Catalogs cards can be displayed as is, though we do have some minor improvements in mind
      * We can potentially add Resource Catalog-specific filters such as the expected data type (`about`) and whether the resource is an IID specific resource (`genre`)
  * Cons: 
    * All filters will be available in the 'All type' tab, thus the issue of messy filters still exists for the default tab (when you visit the search page from the navigation bar rather than by using an actual search)
    * May require users to click to a different tab to see actual search results if they did not specify a type when doing their initial search.
  
2. [Design 2](https://drive.google.com/file/d/122TFE0D9t19N8C4PKgcvfWFcf3RImYis/view?usp=drive_link): Has tabs type-specific tabs, but instead of an 'Any Type' tab (along with the messy filters), it has an `Overview` page which includes a visual summary of the results
  * Pros: 
    * Type-specific filters will be split to type-specific tabs, so there is no messiness with the filters.
    * The Overview/Visual Summary provides a big picture /landscape overview and potential ways of further exploring the data.
    * Users coming via a specific search, will be defaulted to the appropriate tab, but if no specific type is specified, they can be taken to the overview tab for further exploration
    * Resource Catalogs are in their own tab so they don't pollute a search for datasets or computational tools
      * Resource Catalogs cards can be displayed as is, though we do have some minor improvements in mind
      * We can potentially add Resource Catalog-specific filters such as the expected data type (`about`) and whether the resource is an IID specific resource (`genre`) 
    * Provides many of the same visualizations as the `Disease specific pages` or `Program collections specific pages` so that users interested in a disease (for which we don't have a disease-specific page) can still get a partial overview of what's available for that disease.
  * Cons: 
    *  May require users to click to a different tab to see actual search results if they did not specify a type when doing their initial search.

3. [Design 3](https://drive.google.com/file/d/1f9IDGBvm7_XTy0_ZD1g7yLhYJkch_DgK/view?usp=drive_link). This design only has two tabs: Datasets/Resource Catalogs and Computational Tools. In this design, Resource Catalogs are treated as a special element and have their own carousel at the top of the Dataset page to distinguish them from Datasets. Users entering the search page with no specific type in mind will be defaulted to the Dataset/Resource Catalog tab.
  * Pros: 
    * Since the filters are still split appropriately between Dataset/Resource Catalog vs Computational Tool, there is no expected messiness for the filters
    * Highlights the Resource Catalogs and distinguishes them from Datasets almost like an advertisement for the resource catalog
  * Cons: 
    * Requires a complete redesign of the Resource Catalog card view for its display in the carousel
    * The carousel can be annoying to navigate if there are too many Resource Catalogs

**Comment by rshabman** [comment]
After additional discussion at NIAID please proceed as follows: let's move forward with design 3 since it is a solution to displaying resource catalogs, datasets, and computational tools with the proper corresponding metadata.  One point to consider in display 3, it's not clear how many RCs are returned since they are aggregated with datasets - would be nice to have a header that reads 'resource catalogs (x) and datasets (y).  NIAID does still see this is a incremental step as we move towards a dynamic visual summary of metadata in the Portal, which we recognize is not a trivial task.  We can address any questions on the next call.  Thanks.

**Comment by gtsueng** [comment]
This view is now available on staging along with the ResourceCatalog Cards (https://github.com/NIAID-Data-Ecosystem/nde-portal/issues/291). Approval of https://github.com/NIAID-Data-Ecosystem/nde-portal/issues/291 is expected to apply to this issue as well.

**Comment by gtsueng** [comment]
This change is now on production. I am marking this issue as 'pending close out'
