### ISSUE TITLE
[User Interface: Redesign]: UI approaches for funneling user queries to Dataset search or ComputationalTool search

### ISSUE THREAD

**Issue by gtsueng** [NIAID-Data-Ecosystem/nde-portal#242]
### Issue Name

UI approaches for funneling user queries to Dataset search or ComputationalTool search

### Issue Description

Users may wish to search just for computational tools, resource catalogs, or datasets from the get-go. To ensure that users who are searching for one of the three types immediately see relevant results rather than results polluted by one of the other types, create mock ups of potential simple tweaks to the landing page UI which would allow the user to specify the type of thing they're searching for.

Logic Schematic (expected behavior of the ui change)
![Image](https://github.com/NIAID-Data-Ecosystem/nde-portal/assets/9200138/bab32b13-765f-4cb8-a509-d7c89ed3c486)

### Issue Discussion

This issue was raised during the bi-weekly meeting dated 2024.05.28

### WCAG Compliance Check

- [ ] The ui changes are not expected to significantly affect WCAG compliance (ex- wording changes)
- [ ] The ui changes have visual elements which have yet to be tested for WCAG compliance
- [ ] The ui changes have visual elements which have been tested for WCAG compliance
- [ ] The ui changes have passed all checks for WCAG compliance

### Related WBS task

- [ ] Check here if the ui change is centered on the look and feel (https://github.com/NIAID-Data-Ecosystem/nde-roadmap/issues/52)
- [X] Check here if the ui change includes new features (https://github.com/NIAID-Data-Ecosystem/nde-roadmap/issues/53)
- [X] Check here if the ui change was suggested by the NIAID team (https://github.com/NIAID-Data-Ecosystem/nde-roadmap/issues/2)

### For internal use only. Assignee, please select the status of this issue

- [ ] Not yet started
- [ ] In progress
- [ ] Blocked
- [ ] Will not address

### UI change status check list

- [ ] This ui change has yet to be discussed between NIAID, Scripps, Leidos
- [X] This ui change has been discussed/reported between NIAID, Scripps, Leidos
- [x] This ui change has been mocked up
- [x] This ui change has been implemented on Dev
- [x] This ui change has been approved for Staging
- [x] This ui change has been implemented on Staging
- [x] This ui change has been approved for Production
- [x] This ui change has been implemented on Production

**Comment by gtsueng** [comment]
Hi @hartwickma, @lisa-mml, @rshabman, @sudvenk,

Mock ups for how a user might toggle between searching for Datasets, ComputationalTools, or both are now available here: https://drive.google.com/file/d/1ZKexIt7SkbGCb7MTlqIGKCuj1lu4lYwU/view

We are marking this as 'review requested - mock up' and adding it to the list of GH issues on the agenda (to make it easier for you to find, not because we need to discuss it at the upcoming meeting).

**Comment by hartwickma** [comment]
NIAID has added the categorization of 'Ongoing Discussion Item' for issues that are part of ongoing discussions and do not currently require NIAID review. 

Please bring this as an agenda item when Scripps is prepared.

**Comment by hartwickma** [comment]
Hi @gtsueng, thanks for providing these mock-ups. Please move ahead with Option 2. We may provide additional feedback once we have a chance to explore the functionality in staging.

**Comment by gtsueng** [comment]
Thanks for the feedback, @hartwickma, @sudvenk.

@candicecz will proceed with moving Option 2 to Staging.

**Comment by gtsueng** [comment]
Hi @hartwickma, @rshabman, @lisa-mml, @sudvenk,

The ComputationalTool-related UI changes are now on Staging awaiting approval for Production. This includes updates for:
* the [cards](https://github.com/NIAID-Data-Ecosystem/nde-portal/issues/240) 
* the [resources page](https://github.com/NIAID-Data-Ecosystem/nde-portal/issues/267)
* the landing page search options (this issue)

The following updates cannot be applied to staging (due to the STRAPI pages already being published), so the updates will need to be approved in google docs before moving to production:
* the [documentation](https://github.com/NIAID-Data-Ecosystem/nde-portal/issues/268)

The following changes are under investigation:
* [Facets and filter updates](https://github.com/NIAID-Data-Ecosystem/nde-portal/issues/241)

**Comment by hartwickma** [comment]
Hi @gtsueng once the changes to the documentation are finalized, please move the the landing page search options to production.

For future issues with interdependencies please:

1. Avoid adding duplicate notes - it is difficult to determine what to address in order to move the issue forward. Please limit the documentation to what needs to be approved only for that GH issue. If it is too complex for a single GH issue, please provide as an email or an agenda item.

2. Note that moving forward, NIAID will provide a single review for updates to documentation, text, and aesthetics. Please update NIAID once these changes have been implemented and moved to production

**Comment by gtsueng** [comment]
This is now on Production. I am marking this issue as `Pending close out`
