### ISSUE TITLE
[User Interface: Redesign]: Additional UI recommendations from OCGR

### ISSUE THREAD

**Issue by gtsueng** [NIAID-Data-Ecosystem/nde-portal#245]
### Issue Name

Additional UI recommendations from OCGR

### Issue Description

See related [issue #146](https://github.com/NIAID-Data-Ecosystem/nde-crawlers/issues/146) for additional details

- [x] Thank you for adding ROR IDs and links to RePORTER. This will be helpful for NIAID users. Please update to how IDs are displayed on resource cards to be consistent with OCGR recommendations such that anything that is looks like a button should be clickable. For example, either update the ROR ID (under the funder name) to act as a link (because it currently looks like a button) OR change the aesthetic of the ROR ID so that is visually different from the aesthetic around the RePORTER link and does not appear clickable
![image](https://github.com/NIAID-Data-Ecosystem/nde-crawlers/assets/9200138/61098332-5683-4adb-80a4-7d502ce8ae91)

- [x] For some records, the funding information has grant id's which are linked to NIH reporter (as seen in above), but for other records not in LINCS, the ID's appear the same, but are NOT linked. Ensure that linked ids appear differently from unlinked IDs: 
![image](https://github.com/NIAID-Data-Ecosystem/nde-crawlers/assets/9200138/43ea2733-6fea-4eff-bbd8-2bacf46df0c1)
  - [x] Ensure that the funding helper function is run on ResourceCatalogs and every repository so that the identifiers are linked to NIH RePORTER whenever possible and that Funding organizations have either a ROR ID or CrossRef ID whenever possible so that the metadata is formatted consistently and/or has consistent information
  - [x] The front end display of funding information follows OCGR recommendations ensuring that buttons have an appropriate action (like linking to RePORTER) or ensuring that non-interactive elements don't look like buttons

- [x] The term ID is used for both the ‘funding name’ and ‘funding’ column. Consider more specific terms to identify each item. 
![image](https://github.com/NIAID-Data-Ecosystem/nde-crawlers/assets/9200138/2087de2b-1356-44e1-82d8-2c05534012d7)

- [x] Other examples of non-interactive elements that look like button distinguished only by the link out text style and link arrow icon 
![image](https://github.com/NIAID-Data-Ecosystem/nde-crawlers/assets/9200138/b496df29-bb63-4a7d-ab03-4e265dc0a914)

### Issue Discussion

This request was made by the NIAID/ODSET team in an email dated 2024.06.04

### WCAG Compliance Check

- [x] The ui changes are not expected to significantly affect WCAG compliance (ex- wording changes)
- [ ] The ui changes have visual elements which have yet to be tested for WCAG compliance
- [ ] The ui changes have visual elements which have been tested for WCAG compliance
- [ ] The ui changes have passed all checks for WCAG compliance

### Related WBS task

- [X] Check here if the ui change is centered on the look and feel (https://github.com/NIAID-Data-Ecosystem/nde-roadmap/issues/52)
- [ ] Check here if the ui change includes new features (https://github.com/NIAID-Data-Ecosystem/nde-roadmap/issues/53)
- [X] Check here if the ui change was suggested by the NIAID team (https://github.com/NIAID-Data-Ecosystem/nde-roadmap/issues/2)

### For internal use only. Assignee, please select the status of this issue

- [ ] Not yet started
- [ ] In progress
- [ ] Blocked
- [ ] Will not address

### UI change status check list

- [ ] This ui change has yet to be discussed between NIAID, Scripps, Leidos
- [X] This ui change has been discussed/reported between NIAID, Scripps, Leidos
- [ ] This ui change has been mocked up
- [ ] This ui change has been implemented on Dev
- [x] This ui change has been approved for Staging
- [x] This ui change has been implemented on Staging
- [ ] This ui change has been approved for Production
- [ ] This ui change has been implemented on Production

**Comment by candicecz** [comment]
This feedback has been incorporated into the staging instance. You may [view an example here](https://data-staging.niaid.nih.gov/resources?id=dde_136f77a47a3e203a) and I've also attached a screenshot reflecting this change.
![snap](https://github.com/user-attachments/assets/e2e6a7f7-7b0f-4187-b008-a8ce45d1ccf8)

**Comment by gtsueng** [comment]
@hartwickma @lisa-mml @rshabman @sudvenk

The requested changes made via an email dated: 2024.06.04 (subject line: RE: Brief Portal feedback items for Scripps) are now on staging; thus I'm changing the status of this issue to `Review requested - Staging`

The Ask: We seek approval to move these changes to production

**Comment by lisa-mml** [comment]
@gtsueng - thanks for updating the identifier aesthetics to clarify links out. Can you provide more information about the "Funder ID" source (e.g., ROR ID, Crossref::funder_identifier, something else?)?

**Comment by gtsueng** [comment]
@lisa-mml -- For the RePORTER-normalized funder IDs -- most likely Crossref IDs as ROR IDs are URIs. For any non-normalized funder IDs, anything goes. 

With CrossRef's intention to deprecate the CrossRef Open Funder Registry, we plan to migrate to using only ROR IDs in the future. We are awaiting input from the NIAID team on how to best handle the funder information from NIH RePorter (https://github.com/NIAID-Data-Ecosystem/niaid-feedback/issues/143). Once the best path forward has been decided, we'll update the funding helper to use ROR IDs (which will be URIs).

**Comment by hartwickma** [comment]
Hi @gtsueng this sounds like a great discussion item to add to the discussion of #143 'help with funder mapping' As we highlighted in our response to issue #143: _Hi @gtsueng, please bring this as an agenda item in an upcoming bi-weekly meeting._

**Comment by gtsueng** [comment]
@hartwickma @lisa-mml @rshabman @sudvenk

The UI changes have been made an are now on production. I am marking this issue as `pending close out` as it has been addressed on the front-end. Note that there may be back-end improvements needed for this issue to *appear* to be fully addressed (i.e. - for ROR IDs to appear for resource catalogs or for migration to cross ref ids), but those are already separate issues that can be tracked on the corresponding issue:
* [Crossref migration](https://github.com/NIAID-Data-Ecosystem/nde-crawlers/issues/91)
* [ResourceCatalog ROR IDS](https://github.com/NIAID-Data-Ecosystem/nde-crawlers/issues/147)
