### ISSUE TITLE
[User Interface: Redesign]: search function in filters missing potential results

### ISSUE THREAD

**Issue by gtsueng** [NIAID-Data-Ecosystem/nde-portal#246]
### Issue Name

search function in filters missing potential results

### Issue Description

As seen in this example:
![image](https://github.com/NIAID-Data-Ecosystem/nde-portal/assets/9200138/6e7bdb41-609c-40ee-881d-75bb2270792b)

The search term (blue drawn circle) of "Influenze A", brings up a search result which has a standardized value for "Influenza A" in the infectiousAgent/Pathogen field (red drawn circle). However, a search for "influe" in the filter search box does not bring up "Influenza A virus" or any of its aliases (green drawn circle).

### WCAG Compliance Check

- [X] The ui changes are not expected to significantly affect WCAG compliance (ex- wording changes)
- [ ] The ui changes have visual elements which have yet to be tested for WCAG compliance
- [ ] The ui changes have visual elements which have been tested for WCAG compliance
- [ ] The ui changes have passed all checks for WCAG compliance

### Related WBS task

- [X] Check here if the ui change is centered on the look and feel (https://github.com/NIAID-Data-Ecosystem/nde-roadmap/issues/52)
- [ ] Check here if the ui change includes new features (https://github.com/NIAID-Data-Ecosystem/nde-roadmap/issues/53)
- [ ] Check here if the ui change was suggested by the NIAID team (https://github.com/NIAID-Data-Ecosystem/nde-roadmap/issues/2)

### For internal use only. Assignee, please select the status of this issue

- [ ] Not yet started
- [ ] In progress
- [ ] Blocked
- [ ] Will not address

### UI change status check list

- [X] This ui change has yet to be discussed between NIAID, Scripps, Leidos
- [ ] This ui change has been discussed/reported between NIAID, Scripps, Leidos
- [ ] This ui change has been mocked up
- [ ] This ui change has been implemented on Dev
- [ ] This ui change has been approved for Staging
- [ ] This ui change has been implemented on Staging
- [ ] This ui change has been approved for Production
- [ ] This ui change has been implemented on Production

**Comment by gtsueng** [comment]
This is due to the way the `displayName` name field for a defined term is populated. The behavior should be updated such that the `displayName` is populated by the `scientificName` if no `commonName` is available for that definedTerm

**Comment by gtsueng** [comment]
This issue was corrected to be a metadata issue rather than a UI issue and has been addressed by adjusting the value of the `displayName` for records with no `commonName`. I am closing this issue.
