### ISSUE TITLE
[User Interface: Redesign]: UI Quick fixes

### ISSUE THREAD

**Issue by gtsueng** [NIAID-Data-Ecosystem/nde-portal#247]
### Issue Name

UI Quick fixes

### Issue Description

Some potential quick fixes for the site

From CREID:
- [x] Add `sourceOrganization.name` to the Advanced search drop down options list

From OCGR:
- [x] No more split-linking the logo. Entire logo should link to NIAID Data Ecosystem site
- [x] Change language for News to replace "News Releases" with "News & Updates". The language "News Releases" is perceived as Press releases and would require NIAID and HHS review.
![image](https://github.com/NIAID-Data-Ecosystem/nde-portal/assets/9200138/4a518548-cea9-4eb3-8fe4-d3f0dbb2172f)
- [x] Use consistent language for `Help` or `Knowledge Center` header or page. As seen below, it's inconsistent:
![image](https://github.com/NIAID-Data-Ecosystem/nde-portal/assets/9200138/b8485390-63a8-4165-b09a-5175f369de56)
   - either keep header as 'Help', and have breadcrumb say 'Get Help' and change title to 'Browse help topics in our Knowledge Center'
   - Or change all the 'Help' heading to 'Knowledge Center' and the corresponding breadcrumb to 'Knowledge Center'
- [x] Add search button to documentation search for consistency (note - not sure if this is a quick fix or not since the the search behavior on this page is different due to STRAPI, so implement this only if it is easy to do makes sense to do so)
![image](https://github.com/NIAID-Data-Ecosystem/nde-portal/assets/9200138/73bb7f23-4fec-4b90-ad6e-f9e6b2f7ade9)

### Issue Discussion

The changes requested for CREID are not expected to impact nor be noticed by the majority of users, but would make things easier for CREID users. The suggestions from OCGR were discussed at the biweekly meeting dated 2024.07.09. Additional recommendations were made; however, those recommendations require further discussion before implementation

### WCAG Compliance Check

- [ ] The ui changes are not expected to significantly affect WCAG compliance (ex- wording changes)
- [ ] The ui changes have visual elements which have yet to be tested for WCAG compliance
- [X] The ui changes have visual elements which have been tested for WCAG compliance
- [ ] The ui changes have passed all checks for WCAG compliance

### Related WBS task

- [X] Check here if the ui change is centered on the look and feel (https://github.com/NIAID-Data-Ecosystem/nde-roadmap/issues/52)
- [ ] Check here if the ui change includes new features (https://github.com/NIAID-Data-Ecosystem/nde-roadmap/issues/53)
- [X] Check here if the ui change was suggested by the NIAID team (https://github.com/NIAID-Data-Ecosystem/nde-roadmap/issues/2)

### For internal use only. Assignee, please select the status of this issue

- [ ] Not yet started
- [ ] In progress
- [ ] Blocked
- [ ] Will not address

### UI change status check list

- [ ] This ui change has yet to be discussed between NIAID, Scripps, Leidos
- [X] This ui change has been discussed/reported between NIAID, Scripps, Leidos
- [X] This ui change has been mocked up
- [ ] This ui change has been implemented on Dev
- [X] This ui change has been approved for Staging
- [ ] This ui change has been implemented on Staging
- [x] This ui change has been approved for Production
- [x] This ui change has been implemented on Production

**Comment by candicecz** [comment]
All changes are live on [staging](https://data-staging.niaid.nih.gov/). 

Note that the links embedded within the knowledge center content are still pointing to the old urls `/docs` not `/knowledge-center`. We will need to update this in Strapi when approved for production - we cannot do it sooner since this will break the production instance's links (which uses the route `/docs`).

**Comment by gtsueng** [comment]
Hi @hartwickma @lisa-mml @rshabman @sudvenk

While we expect that these quick fix changes do not need NIAID approval to move to production based on the [comment](https://github.com/NIAID-Data-Ecosystem/nde-portal/issues/209#issuecomment-1898920342) for https://github.com/NIAID-Data-Ecosystem/nde-portal/issues/209, we are erring on the side of caution and requesting approval to move these changes forward to production. If in the future we should not seek approval for these types of changes, please let us know and we'll adjust as needed. Thanks!

The Ask: We seek approval to push these changes to Production

**Comment by hartwickma** [comment]
Thank you, if these are in-line with what has been discussed please proceed to move to prodcution, NIAID does not need to formally approve agreed-upon changes. We are not able to discern the request related to CREID. Please provide more information for what change has been made to aid CREID data users?

**Comment by gtsueng** [comment]
@hartwickma The CREID portal/schema has an additional field (`sourceOrganization`) which is not displayed anywhere in the portal. In order to facilitate their use of this field for searching/filtering we have added it as an menu option in the Advanced Search drop down menu. This field is not available and does not affect any other repositories.

The remaining changes were quick fixes discussed in the 2024.07.10 biweekly call. We will push these changes to production.

**Comment by candicecz** [comment]
These changes are now available on the[ production instance](https://data.niaid.nih.gov/). 

1. `sourceOrganization` is pending data changes to the API and is not available yet.
2. Links embedded within the knowledge center content have been updated to reflect the route change from `/docs` to `knowledge-center`

**Comment by gtsueng** [comment]
@hartwickma @sudvenk the UI quick changes that were previously discussed at the last bi-weekly meeting have been implemented on Production. I am marking this issue as `pending close out` and will close it after a week if there are no further changes needed regarding this particular issue.
