### ISSUE TITLE
[User Interface: Redesign]: Search result pagination on bottom

### ISSUE THREAD

**Issue by gtsueng** [NIAID-Data-Ecosystem/nde-portal#249]
### Issue Name

Search result pagination on bottom

### Issue Description

Currently, the pagination for the search results is at the top. 
![image](https://github.com/user-attachments/assets/6b305d04-a99c-4438-a7e1-968a4a879d45)

But, a user might not know if they need to go to the next page, until after they've reviewed what's on the current page. This means that the user will scroll down to browse through the records, and then in order to see the next set of records, they need to scroll all the way back up.

Should pagination elements for the search results be moved (or included) at the bottom?

### WCAG Compliance Check

- [ ] The ui changes are not expected to significantly affect WCAG compliance (ex- wording changes)
- [ ] The ui changes have visual elements which have yet to be tested for WCAG compliance
- [ ] The ui changes have visual elements which have been tested for WCAG compliance
- [ ] The ui changes have passed all checks for WCAG compliance

### Related WBS task

- [X] Check here if the ui change is centered on the look and feel (https://github.com/NIAID-Data-Ecosystem/nde-roadmap/issues/52)
- [ ] Check here if the ui change includes new features (https://github.com/NIAID-Data-Ecosystem/nde-roadmap/issues/53)
- [ ] Check here if the ui change was suggested by the NIAID team (https://github.com/NIAID-Data-Ecosystem/nde-roadmap/issues/2)

### For internal use only. Assignee, please select the status of this issue

- [ ] Not yet started
- [ ] In progress
- [ ] Blocked
- [ ] Will not address

### UI change status check list

- [X] This ui change has yet to be discussed between NIAID, Scripps, Leidos
- [ ] This ui change has been discussed/reported between NIAID, Scripps, Leidos
- [ ] This ui change has been mocked up
- [ ] This ui change has been implemented on Dev
- [ ] This ui change has been approved for Staging
- [ ] This ui change has been implemented on Staging
- [ ] This ui change has been approved for Production
- [ ] This ui change has been implemented on Production

**Comment by gtsueng** [comment]
This has been fixed.
