### ISSUE TITLE
[User Interface: Redesign]: Investigate increasing prominence of description in record view

### ISSUE THREAD

**Issue by gtsueng** [NIAID-Data-Ecosystem/nde-portal#251]
### Issue Name

Investigate increasing prominence of description in record view

### Issue Description

In order to improve the display of record descriptions, we should create descriptions of more consistent length. See https://github.com/NIAID-Data-Ecosystem/nde-portal/issues/147 for more details. These created descriptions should be saved to the abstract field.

Some things to take into consideration:
* length limitations of ChatGPT before hallucinating results for measurementTechniques: https://docs.google.com/spreadsheets/d/1crfLDl5_c7jZ47JefhOCf6tx_cM-u8AkK6rsXttM6s8/edit?gid=1639648736#gid=1639648736
* Title length optimization for SEO is ~70-80 characters
* Description length optimization for SEO is ~140 - 160 characters
* The ~<400 character range appears to have around the same number of records as the ~<50 word range (and there are ~1 million records within this character/word length range)
* The current character limitation for the display of the description in the current search results/card view is ~180 characters. Descriptions greater than this length are displayable after clicking on the interactive element.

Steps:
- [ ] Design a Lyssna study to determine description length preferences (test 3-5 length ranges) and it's display in the record view
- [ ] Use ChatGPT to generate sample descriptions within length ranges
- [ ] Run Lyssna study using the GPT-generated sample descriptions
- [ ] [Use GPT to generate short descriptions (abstracts) based on the results of the Lyssna study for records where the description length is >400 characters.](https://github.com/NIAID-Data-Ecosystem/nde-crawlers/issues/159)

### WCAG Compliance Check

- [X] The ui changes are not expected to significantly affect WCAG compliance (ex- wording changes)
- [ ] The ui changes have visual elements which have yet to be tested for WCAG compliance
- [ ] The ui changes have visual elements which have been tested for WCAG compliance
- [ ] The ui changes have passed all checks for WCAG compliance

### Related WBS task

- [ ] Check here if the ui change is centered on the look and feel (https://github.com/NIAID-Data-Ecosystem/nde-roadmap/issues/52)
- [ ] Check here if the ui change includes new features (https://github.com/NIAID-Data-Ecosystem/nde-roadmap/issues/53)
- [ ] Check here if the ui change was suggested by the NIAID team (https://github.com/NIAID-Data-Ecosystem/nde-roadmap/issues/2)

### For internal use only. Assignee, please select the status of this issue

- [ ] Not yet started
- [ ] In progress
- [ ] Blocked
- [ ] Will not address

### UI change status check list

- [X] This ui change has yet to be discussed between NIAID, Scripps, Leidos
- [ ] This ui change has been discussed/reported between NIAID, Scripps, Leidos
- [ ] This ui change has been mocked up
- [ ] This ui change has been implemented on Dev
- [ ] This ui change has been approved for Staging
- [ ] This ui change has been implemented on Staging
- [ ] This ui change has been approved for Production
- [ ] This ui change has been implemented on Production

**Comment by gtsueng** [comment]
Per discussions on 2024.09.23, we will forgo conducting user studies to determine the optimal length of generated summaries, and use the ~170 word count used by Scientific Data (as suggested by Lilliana). The summary should include 1-2 sentences detailing the method and experimental conditions. We will proceed with generating mock-ups that will visually prioritize summary information (but also indicates clearly that the summary information was generated using genAI). This information will be stored in a separate metadata field, `disambiguatingDescription` (while the original description field will be kept un-alterated).

@ZubairQazi will edit the prompt according to the requirements: 170 words max; of which 1-2 sentences should detail method and experimental conditions (only if available, do not make it up if not available). He will then, run the prompt on ClinEpiDB records as ClinEpiDB is likely to have longer description fields (with method/experimental condition info in description).

Once Zubair generates these summaries for ClinEpiDB, @DylanWelzel will add them to the records on Staging. @DylanWelzel please use the field `disambiguatingDescription` for the AI-generated summaries. The `abstract` field is already in use by ~1000 records or so, and we don't want to overwrite existing ingested data with AI-generated data. Instead, we will use the field `disambiguatingDescription` which is a schema.org base property for the top/root level class Thing.

@jal347 please add `disambiguatingDescription` to the ES mapping as needed to support this effort.

@candicecz has already generated some initial designs for how this data will be displayed

@leandrocollares will set up a Lyssna study to determine the best design.

**Comment by gtsueng** [comment]
The AI-generated summaries have been on Staging since before the creation of [this issue](https://github.com/NIAID-Data-Ecosystem/niaid-feedback/issues/161).

As of 2024.11.19, AI-generated summaries have also been added to ImmPort for records where the description is >200 words in length.
