### ISSUE TITLE
[User Interface: Redesign]: Add "getting started" section to landing page

### ISSUE THREAD

**Issue by gtsueng** [NIAID-Data-Ecosystem/nde-portal#253]
### Issue Name

Add "getting started" section to landing page

### Issue Description

The "getting started" section suggested by OCGR:
![image](https://github.com/user-attachments/assets/f0cc9c45-428c-4c6f-8eb3-1a48680e263f)

Has been found to be a desirable element in User studies (https://github.com/NIAID-Data-Ecosystem/nde-portal/issues/248) and during discussions with NIAID

We would like to proceed with including this element to the landing page, as it's something we all agree would be valuable.

Here is a mock up of the landing page with the new "getting started" section suggested by OCGR, incorporating the feedback from the [Lyssna study on whether or not to include the sources table on the landing page](https://github.com/NIAID-Data-Ecosystem/nde-portal/issues/248)

The Ask: 
1. We request that NIAID provide an approved image asset for use in this 'getting started' element 
2. We seek approval to implement the changes in the mockup (which include this 'getting started' element to STAGING

### Issue Discussion

This design element was discussed at the biweekly meeting dated 2024.07.09

### Mockup URL

https://drive.google.com/file/d/1UPkBf2SXePe_8i4Z5TLrCGR5Lk5Ttfkh/view?usp=sharing

### WCAG Compliance Check

- [X] The ui changes are not expected to significantly affect WCAG compliance (ex- wording changes)
- [ ] The ui changes have visual elements which have yet to be tested for WCAG compliance
- [ ] The ui changes have visual elements which have been tested for WCAG compliance
- [ ] The ui changes have passed all checks for WCAG compliance

### Related WBS task

- [ ] Check here if the ui change is centered on the look and feel (https://github.com/NIAID-Data-Ecosystem/nde-roadmap/issues/52)
- [ ] Check here if the ui change includes new features (https://github.com/NIAID-Data-Ecosystem/nde-roadmap/issues/53)
- [ ] Check here if the ui change was suggested by the NIAID team (https://github.com/NIAID-Data-Ecosystem/nde-roadmap/issues/2)

### For internal use only. Assignee, please select the status of this issue

- [ ] Not yet started
- [ ] In progress
- [ ] Blocked
- [ ] Will not address

### UI change status check list

- [ ] This ui change has yet to be discussed between NIAID, Scripps, Leidos
- [X] This ui change has been discussed/reported between NIAID, Scripps, Leidos
- [X] This ui change has been mocked up
- [x] This ui change has been implemented on Dev
- [x] This ui change has been approved for Staging
- [x] This ui change has been implemented on Staging
- [x] This ui change has been approved for Production
- [x] This ui change has been implemented on Production

**Comment by lisa-mml** [comment]
Thanks @gtsueng. This is fine to move to staging. We will share the image via email later today.

**Comment by gtsueng** [comment]
@hartwickma, @rshabman, @lisa-mml, @sudvenk

We have implemented these changes to staging and seek approval to move this to Production

**Comment by hartwickma** [comment]
Hi @gtsueng thank you for this updated version of the landing page. Please move this version to production and we may discuss additional, future changes and updates.

**Comment by gtsueng** [comment]
I am marking this issue as `pending close out` and will close it after a week if there are no additional changes to be made with regards to the inclusion of the `getting started` section on the landing page
