### ISSUE TITLE
[User Interface: Redesign]: Computational Tool Resources page update

### ISSUE THREAD

**Issue by gtsueng** [NIAID-Data-Ecosystem/nde-portal#267]
### Issue Name

Computational Tool Resources page update

### Issue Description

The Computational Tool Resources page should be updated to reflect the [improvements made to the Computational Tools cards](https://github.com/NIAID-Data-Ecosystem/nde-portal/issues/240)

### Issue Discussion

This issue was discussed at the biweekly meeting dated 2024.11.12

### WCAG Compliance Check

- [ ] The ui changes are not expected to significantly affect WCAG compliance (ex- wording changes)
- [X] The ui changes have visual elements which have yet to be tested for WCAG compliance
- [ ] The ui changes have visual elements which have been tested for WCAG compliance
- [ ] The ui changes have passed all checks for WCAG compliance

### Related WBS task

- [X] Check here if the ui change is centered on the look and feel (https://github.com/NIAID-Data-Ecosystem/nde-roadmap/issues/52)
- [ ] Check here if the ui change includes new features (https://github.com/NIAID-Data-Ecosystem/nde-roadmap/issues/53)
- [ ] Check here if the ui change was suggested by the NIAID team (https://github.com/NIAID-Data-Ecosystem/nde-roadmap/issues/2)

### For internal use only. Assignee, please select the status of this issue

- [ ] Not yet started
- [x] In progress
- [ ] Blocked
- [ ] Will not address

### UI change status check list

- [ ] This ui change has yet to be discussed between NIAID, Scripps, Leidos
- [X] This ui change has been discussed/reported between NIAID, Scripps, Leidos
- [x] This ui change has been mocked up
- [x] This ui change has been implemented on Dev
- [x] This ui change has been approved for Staging
- [x] This ui change has been implemented on Staging
- [x] This ui change has been approved for Production
- [x] This ui change has been implemented on Production

**Comment by gtsueng** [comment]
Hi @hartwickma, @rshabman, @lisa-mml, @sudvenk,

The ComputationalTool-related UI changes are now on Staging awaiting approval for Production. This includes updates for:
* the [cards](https://github.com/NIAID-Data-Ecosystem/nde-portal/issues/240) 
* the resources page (this issue)
* the [landing page search options](https://github.com/NIAID-Data-Ecosystem/nde-portal/issues/242)

The following updates cannot be applied to staging (due to the STRAPI pages already being published), so the updates will need to be approved in google docs before moving to production:
* the [documentation](https://github.com/NIAID-Data-Ecosystem/nde-portal/issues/268)

The following changes are under investigation:
* [Facets and filter updates](https://github.com/NIAID-Data-Ecosystem/nde-portal/issues/241)

**Comment by gtsueng** [comment]
ComputationalTool is now on production. I am marking this issue as `pending close out`
