### ISSUE TITLE
[User Interface: Redesign]: Update copy for Data access buttons

### ISSUE THREAD

**Issue by gtsueng** [NIAID-Data-Ecosystem/nde-portal#270]
### Issue Name

 Update copy for Data access buttons

### Issue Description

Now that ComputationalTools are in the works and ResourceCatalogs are available in the NIAID Data Ecosystem, the Data Access button should be updated:

It looks fine for datasets:
![image](https://github.com/user-attachments/assets/4509a0ce-c4bd-44d0-aac2-263da429a910)

But may seem a little confusing for ResourceCatalogs and ComputationalTools
![image](https://github.com/user-attachments/assets/f6254e0d-a78a-4345-bd8b-f029abb42415)

### Issue Discussion

This change is expected to be a minor/quick fix and should potentially lean on the terminology study that Emily on the subject of using 'records', 'resources', 'dataset repository', etc.

### WCAG Compliance Check

- [X] The ui changes are not expected to significantly affect WCAG compliance (ex- wording changes)
- [ ] The ui changes have visual elements which have yet to be tested for WCAG compliance
- [ ] The ui changes have visual elements which have been tested for WCAG compliance
- [ ] The ui changes have passed all checks for WCAG compliance

### Related WBS task

- [X] Check here if the ui change is centered on the look and feel (https://github.com/NIAID-Data-Ecosystem/nde-roadmap/issues/52)
- [ ] Check here if the ui change includes new features (https://github.com/NIAID-Data-Ecosystem/nde-roadmap/issues/53)
- [ ] Check here if the ui change was suggested by the NIAID team (https://github.com/NIAID-Data-Ecosystem/nde-roadmap/issues/2)

### For internal use only. Assignee, please select the status of this issue

- [ ] Not yet started
- [ ] In progress
- [ ] Blocked
- [ ] Will not address

### UI change status check list

- [ ] This ui change has yet to be discussed between NIAID, Scripps, Leidos
- [ ] This ui change has been discussed/reported between NIAID, Scripps, Leidos
- [ ] This ui change has been mocked up
- [ ] This ui change has been implemented on Dev
- [ ] This ui change has been approved for Staging
- [ ] This ui change has been implemented on Staging
- [ ] This ui change has been approved for Production
- [ ] This ui change has been implemented on Production

**Comment by candicecz** [comment]
@ginger based on this [issue](https://github.com/NIAID-Data-Ecosystem/nde-portal/issues/234). I think we chose "view resource" to be applied for all types of records. Let me know if that's correct and I'll make the change on `dev` + `staging`.

Separately, should we leave the resource page heading as `Data Access` or do you have another suggestion?
Thanks!

**Comment by gtsueng** [comment]
@candicecz, Yes --Since we've already changed the card button to `view resource` for Datasets and ResourceCatalogs awhile back, it makes sense to use that term for CompTools as well. 

For the "Data Access" header and the "Access Data" button on the Resource page, it would be more consistent to use "Resource Access" and "Access Resource".

**Comment by candicecz** [comment]
![image](https://github.com/user-attachments/assets/e62eae83-cbc6-43b5-b8b2-85d40c4895bf)
Updated on [dev ](https://nde-dev.biothings.io/resources?id=dde_b3bb013bc893ca80) and [staging](https://data-staging.niaid.nih.gov/resources?id=dde_b3bb013bc893ca80)

**Comment by gtsueng** [comment]
@candicecz can you fix this to be consistent with the rest?

![Image](https://github.com/user-attachments/assets/06322e7b-109a-484e-8330-1157fde62c64)

**Comment by candicecz** [comment]
@gtsueng would you like it to say "Search for resources"?

**Comment by gtsueng** [comment]
@candicecz is "Search for datasets, tools, and other resources" too long? If so, "Search for resources" is fine.

**Comment by gtsueng** [comment]
These changes are all on Production. I am marking this issue as `pending close out`
