### ISSUE TITLE
[User Interface: Redesign]: Change wording of 'any specified' in filter

### ISSUE THREAD

**Issue by gtsueng** [NIAID-Data-Ecosystem/nde-portal#271]
### Issue Name

Change wording of 'any specified' in filter

### Issue Description

Based on multiple discussions, the term `any specified` in the filter is confusing, however, the function it provides is desirable. Change the wording of the `any specified` in the filters to match the filter name. For example:
* Program Collections, `any specified` --> `any program collection`
* Health Condition, `any specified` --> `any health condition` ...  etc

### Issue Discussion

This issue was discussed on multiple occasions (including meetings with OCGR), with the most recent being the bi-weekly meeting dated 2024.11.26

### WCAG Compliance Check

- [X] The ui changes are not expected to significantly affect WCAG compliance (ex- wording changes)
- [ ] The ui changes have visual elements which have yet to be tested for WCAG compliance
- [ ] The ui changes have visual elements which have been tested for WCAG compliance
- [ ] The ui changes have passed all checks for WCAG compliance

### Related WBS task

- [X] Check here if the ui change is centered on the look and feel (https://github.com/NIAID-Data-Ecosystem/nde-roadmap/issues/52)
- [ ] Check here if the ui change includes new features (https://github.com/NIAID-Data-Ecosystem/nde-roadmap/issues/53)
- [ ] Check here if the ui change was suggested by the NIAID team (https://github.com/NIAID-Data-Ecosystem/nde-roadmap/issues/2)

### For internal use only. Assignee, please select the status of this issue

- [ ] Not yet started
- [ ] In progress
- [ ] Blocked
- [ ] Will not address

### UI change status check list

- [ ] This ui change has yet to be discussed between NIAID, Scripps, Leidos
- [X] This ui change has been discussed/reported between NIAID, Scripps, Leidos
- [ ] This ui change has been mocked up
- [ ] This ui change has been implemented on Dev
- [X] This ui change has been approved for Staging
- [ ] This ui change has been implemented on Staging
- [X] This ui change has been approved for Production
- [ ] This ui change has been implemented on Production
