### ISSUE TITLE
[User Interface: Redesign]: Limit the number of topicCategory items displayed in card view

### ISSUE THREAD

**Issue by gtsueng** [NIAID-Data-Ecosystem/nde-portal#274]
### Issue Name

Limit the number of topicCategory items displayed in card view

### Issue Description

Some records like Figshare may have a lot of topicCategories due to mappings -- this will clutter the card view. Limit the number of topicCategory items displayed in the card view

### Issue Discussion

This is considered a minor change and will not be discussed extensively

### WCAG Compliance Check

- [X] The ui changes are not expected to significantly affect WCAG compliance (ex- wording changes)
- [ ] The ui changes have visual elements which have yet to be tested for WCAG compliance
- [ ] The ui changes have visual elements which have been tested for WCAG compliance
- [ ] The ui changes have passed all checks for WCAG compliance

### Related WBS task

- [X] Check here if the ui change is centered on the look and feel (https://github.com/NIAID-Data-Ecosystem/nde-roadmap/issues/52)
- [ ] Check here if the ui change includes new features (https://github.com/NIAID-Data-Ecosystem/nde-roadmap/issues/53)
- [ ] Check here if the ui change was suggested by the NIAID team (https://github.com/NIAID-Data-Ecosystem/nde-roadmap/issues/2)

### For internal use only. Assignee, please select the status of this issue

- [ ] Not yet started
- [ ] In progress
- [ ] Blocked
- [ ] Will not address

### UI change status check list

- [X] This ui change has yet to be discussed between NIAID, Scripps, Leidos
- [ ] This ui change has been discussed/reported between NIAID, Scripps, Leidos
- [ ] This ui change has been mocked up
- [ ] This ui change has been implemented on Dev
- [X] This ui change has been approved for Staging
- [ ] This ui change has been implemented on Staging
- [ ] This ui change has been approved for Production
- [ ] This ui change has been implemented on Production

**Comment by candicecz** [comment]
Changes are applied on all instances.
Old:
![image](https://github.com/user-attachments/assets/05270e7c-8ce1-4f36-a58b-6eba967755eb)

Update:
![image](https://github.com/user-attachments/assets/56d0ca21-650e-4b3d-adb2-0e5f29762ccc)
