### ISSUE TITLE
[User Interface: Redesign]: Add `Registered Access` to list of options in Landing Page Source table Access column

### ISSUE THREAD

**Issue by gtsueng** [NIAID-Data-Ecosystem/nde-portal#277]
### Issue Name

Add `Registered Access` to list of options in Landing Page Source table Access column

### Issue Description

The `Registered Access` column should refer to repositories where the `conditionsOfAccess` values are set to `closed`

@leandrocollares this should be a Quick Fix. Note that the data needed to visualize this is [pending updates to the parsers](https://github.com/NIAID-Data-Ecosystem/nde-crawlers/issues/222) by @jal347 and some [repository-level metadata updates](https://github.com/NIAID-Data-Ecosystem/nde-metadata-corrections/issues/28) that have been assigned to @DylanWelzel and @jal347 

### Issue Discussion

This issue addresses: https://github.com/NIAID-Data-Ecosystem/niaid-feedback/issues/169

### WCAG Compliance Check

- [X] The ui changes are not expected to significantly affect WCAG compliance (ex- wording changes)
- [ ] The ui changes have visual elements which have yet to be tested for WCAG compliance
- [ ] The ui changes have visual elements which have been tested for WCAG compliance
- [ ] The ui changes have passed all checks for WCAG compliance

### Related WBS task

- [ ] Check here if the ui change is centered on the look and feel (https://github.com/NIAID-Data-Ecosystem/nde-roadmap/issues/52)
- [ ] Check here if the ui change includes new features (https://github.com/NIAID-Data-Ecosystem/nde-roadmap/issues/53)
- [X] Check here if the ui change was suggested by the NIAID team (https://github.com/NIAID-Data-Ecosystem/nde-roadmap/issues/2)

### For internal use only. Assignee, please select the status of this issue

- [ ] Not yet started
- [ ] In progress
- [ ] Blocked
- [ ] Will not address

### UI change status check list

- [ ] This ui change has yet to be discussed between NIAID, Scripps, Leidos
- [X] This ui change has been discussed/reported between NIAID, Scripps, Leidos
- [ ] This ui change has been mocked up
- [ ] This ui change has been implemented on Dev
- [X] This ui change has been approved for Staging
- [ ] This ui change has been implemented on Staging
- [X] This ui change has been approved for Production
- [ ] This ui change has been implemented on Production

**Comment by candicecz** [comment]
![image](https://github.com/user-attachments/assets/e40dface-f46b-4b94-894f-9a2fe98ed134)
![image](https://github.com/user-attachments/assets/f453a2f7-cb4e-420e-bd69-e18a00013797)

`Registered Access` has been added to the portal

**Comment by gtsueng** [comment]
With these changes, I'm marking this issue as `pending close out`
